# Generated by Django 4.2.2 on 2023-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("image", models.ImageField(null=True, upload_to="query_posts")),
                ("issue_name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("more_details", models.TextField()),
            ],
        ),
    ]
