# Generated by Django 4.0.5 on 2023-10-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querypost',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='querypost',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
