# Generated by Django 4.0.5 on 2023-10-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squery', '0002_querypost_date_alter_querypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querypost',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
