# Generated by Django 4.2.2 on 2023-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squery", "0007_alter_likes_post_alter_querypost_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(max_length=150)),
                ("file", models.FileField(upload_to="certificates")),
            ],
        ),
        migrations.AddField(
            model_name="querypost",
            name="certificates",
            field=models.ManyToManyField(
                related_name="rewards", to="squery.certificate"
            ),
        ),
    ]
