# Generated by Django 4.2.2 on 2023-10-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squery", "0009_certificate_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="file",
            field=models.FileField(upload_to="rewards"),
        ),
    ]
