# Generated by Django 4.2.2 on 2023-11-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squery", "0011_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="querypost",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
